[package]
name = "parami-runtime"
version = "2.0.1"
authors = ["Parami Devs <info@parami.io>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]

# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.102", optional = true }
static_assertions = "1.1.0"
hex-literal = { version = "0.3.1", optional = true }
log = { version = "0.4.14", default-features = false }

# primitives
parami-primitives = { version = "2.0.0", default-features = false, path = "../primitives" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-staking = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", optional = true }
sp-session = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }

# frame dependencies
frame-executive = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false, optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-authorship = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-assets = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-babe = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-bounties = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-democracy = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-election-provider-multi-phase = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-mmr = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-offences = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-offences-benchmarking = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false, optional = true }
pallet-proxy = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-recovery = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", features = ["historical"], default-features = false }
pallet-session-benchmarking = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false, optional = true }
pallet-staking = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-society = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-tips = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-treasury = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }
pallet-vesting = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09", default-features = false }

# orml
orml-nft = { path = "../orml/nft", default-features = false }
orml-auction = { path = "../orml/auction", default-features = false }

# own pallets
parami-account-linker = { path = "../pallets/account-linker", default-features = false }
parami-did = { path = "../pallets/did", default-features = false }
parami-airdrop = { path = "../pallets/airdrop", default-features = false }
chainbridge = { path = "../pallets/chainbridge", default-features = false }
parami-cross-assets = { path = "../pallets/cross-assets", default-features = false }
parami-assets = { path = "../pallets/assets", default-features = false }
parami-nft = { path = "../pallets/nft", default-features = false }
parami-auction = { path = "../pallets/auction", default-features = false }
parami-swap = { path = "../pallets/swap", default-features = false }
parami-magic-link = { path = "../pallets/magic-link", default-features = false }

parami-ad = { path = "../pallets/ad", default-features = false }
parami-bridge = { package = "parami-bridge", path = "../pallets/bridge", default-features = false }

[build-dependencies]
prost-build = "0.8"
substrate-wasm-builder = { version = "4.0.0" }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", tag="monthly-2021-09" }

[features]
default = ["std"]
with-tracing = [ "frame-executive/with-tracing" ]
std = [
    "sp-authority-discovery/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "sp-consensus-babe/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "pallet-bounties/std",
    "sp-block-builder/std",
    "codec/std",
    "pallet-collective/std",
    "pallet-contracts/std",
    "pallet-contracts-primitives/std",
    "pallet-contracts-rpc-runtime-api/std",
    "pallet-democracy/std",
    "pallet-elections-phragmen/std",
    "frame-executive/std",
    "frame-election-provider-support/std",
    "pallet-grandpa/std",
    "pallet-im-online/std",
    "sp-inherents/std",
    "pallet-membership/std",
    "pallet-mmr/std",
    "pallet-multisig/std",
    "pallet-identity/std",
    "pallet-scheduler/std",
    "parami-primitives/std",
    "sp-offchain/std",
    "pallet-offences/std",
    "pallet-proxy/std",
    "sp-core/std",
    "pallet-randomness-collective-flip/std",
    "sp-std/std",
    "serde",
    "pallet-session/std",
    "sp-api/std",
    "sp-runtime/std",
    "sp-staking/std",
    "pallet-staking/std",
    "sp-keyring",
    "sp-session/std",
    "pallet-sudo/std",
    "frame-support/std",
    "frame-benchmarking/std",
    "frame-system-rpc-runtime-api/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "pallet-tips/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-transaction-payment/std",
    "pallet-treasury/std",
    "sp-transaction-pool/std",
    "pallet-utility/std",
    "sp-version/std",
    "pallet-society/std",
    "pallet-recovery/std",
    "pallet-vesting/std",
    "log/std",
    "sp-npos-elections/std",
    "parami-did/std",
    "parami-airdrop/std",
    "chainbridge/std",
    "parami-cross-assets/std",
    "orml-nft/std",
    "orml-auction/std",
    "pallet-assets/std",
    "parami-swap/std",
    "parami-assets/std",
    "parami-ad/std",
    "parami-bridge/std",
    "parami-nft/std",
    "parami-auction/std",
    "parami-magic-link/std"
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-babe/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-bounties/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-contracts/runtime-benchmarks",
    "pallet-democracy/runtime-benchmarks",
    "pallet-elections-phragmen/runtime-benchmarks",
    "pallet-grandpa/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-mmr/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-scheduler/runtime-benchmarks",
    "pallet-society/runtime-benchmarks",
    "pallet-staking/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-tips/runtime-benchmarks",
    "pallet-treasury/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-vesting/runtime-benchmarks",
    "pallet-offences-benchmarking",
    "pallet-session-benchmarking",
    "frame-system-benchmarking",
    "hex-literal",
    "parami-did/runtime-benchmarks",
    "pallet-assets/runtime-benchmarks",
    "parami-nft/runtime-benchmarks"
]
