[package]
name = "parami-ad"
version = "0.2.0"
authors = ["Parami Team <info@parami.io>"]
edition = "2018"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["derive", "max-encoded-len"] }
serde = { version = "1.0.111", optional = true }

# primitives
parami-primitives = { version = "2.0.0", path = "../../primitives", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }

# frame dependencies
frame-support = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", version = "3.0.0", default-features = false, optional = true }

parami-did = { path = "../did", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", version = "3.0.0" }
pallet-utility = { git = 'https://github.com/paritytech/substrate.git', version = "3.0.0" }
pallet-proxy = { git = 'https://github.com/paritytech/substrate.git', version = "3.0.0" }

[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "pallet-balances/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "parami-did/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
